Added tool-versions to allow local development with asdf
lens-protocol/core pull request #58
Opened 2022-03-17 13:53 UTC by nirga

Added spec for Solidity and Nodejs versions (matching the ones in the `Dockerfile`) to allow development using a local stack with [asdf](https://github.com/asdf-vm/asdf), as an alternative for developing over Docker.

2022-03-30 11:29 UTC, donosonaumczuk requested changes
Thanks for the contribution @nirga. I ask you a few changes to match the used versions

2022-03-30 11:29 UTC, donosonaumczuk commented on .tool-versions
> +nodejs 16.14.1
I'm not familiarized with `asdf`, but it's possible to put just this?

```suggestion
nodejs 16
```

2022-03-30 11:29 UTC, donosonaumczuk commented on .tool-versions
> +solidity 0.8.7
We are using this Solidity version

```suggestion
solidity 0.8.10
```

2022-03-30 11:32 UTC, donosonaumczuk commented
Also @nirga, do you mind sharing the steps to have it working using `asdf` ? So I can include it in the README file (or you can add it directly to the README if you want)

2022-11-03 17:54 UTC, Zer0dot commented
Closing this at it seems stale-- happy to discuss further though should the need arise!

2022-11-03 17:54 UTC, closed without merging